version: 2
jobs:
  build_linux:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: 
          name: Install Dependencies
          command: |
            apt update 
            apt install -y curl clang cmake git uuid-dev libx11-xcb-dev libgl1-mesa-dev
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt install -y git-lfs
      - checkout
      - run:
          name: Git LFS Checkout 
          command:
            git config lfs.url https://lfs.chenwenli.com
            git lfs fetch
            git lfs checkout
      - run: 
          name: Build
          command:
            sh ./build_crossguid.sh
            sh ./build_opengex.sh
            sh ./build_zlib.sh
            bash ./build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      

